# Generated by Django 4.2.3 on 2023-07-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='nominations',
        ),
        migrations.CreateModel(
            name='NominationAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.nomination')),
            ],
        ),
        migrations.CreateModel(
            name='MemberNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(default=[])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.member')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.categorynomination')),
            ],
        ),
        migrations.AddField(
            model_name='categorynomination',
            name='event_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventcategory'),
        ),
        migrations.AddField(
            model_name='categorynomination',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.nomination'),
        ),
    ]
