# Generated by Django 4.2.3 on 2023-07-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_nomination_membernomination_category_nomination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorynomination',
            options={'verbose_name': 'Номинации категорий', 'verbose_name_plural': 'Номинации категорий'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Категории мероприятия', 'verbose_name_plural': 'Категории мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='eventstaff',
            options={'verbose_name': 'Судья', 'verbose_name_plural': 'Судьи'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='membernomination',
            options={'verbose_name': 'Номинация участника', 'verbose_name_plural': 'Номинации участника'},
        ),
        migrations.AlterModelOptions(
            name='winnercategory',
            options={'verbose_name': 'Гран-при', 'verbose_name_plural': 'Гран-при'},
        ),
        migrations.AlterModelOptions(
            name='winnernomination',
            options={'verbose_name': 'Победитель номинации', 'verbose_name_plural': 'Победители номинации'},
        ),
        migrations.AddField(
            model_name='membernomination',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='membernomination',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='membernomination',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='membernomination',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
