# Generated by Django 4.2.3 on 2023-08-31 12:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_result_score_retail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernomination',
            name='photo_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[500, 300], upload_to=''),
        ),
        migrations.AlterField(
            model_name='membernomination',
            name='photo_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[500, 300], upload_to=''),
        ),
        migrations.AlterField(
            model_name='membernomination',
            name='photo_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[500, 300], upload_to=''),
        ),
        migrations.AlterField(
            model_name='membernomination',
            name='photo_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[500, 300], upload_to=''),
        ),
    ]
