# Generated by Django 4.2.3 on 2024-01-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_membernomination_photo_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberNominationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('before_after', models.CharField(choices=[('BE', 'До'), ('AF', 'После')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='winnernomination',
            name='category',
        ),
        migrations.RemoveField(
            model_name='winnernomination',
            name='member',
        ),
        migrations.RemoveField(
            model_name='winnernomination',
            name='nomination',
        ),
        migrations.RemoveField(
            model_name='membernomination',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='membernomination',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='membernomination',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='membernomination',
            name='photo_4',
        ),
        migrations.AddField(
            model_name='nomination',
            name='photos_conf',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='membernomination',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membernom', to='events.member'),
        ),
        migrations.AlterField(
            model_name='nominationattribute',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='WinnerCategory',
        ),
        migrations.DeleteModel(
            name='WinnerNomination',
        ),
        migrations.AddField(
            model_name='membernominationphoto',
            name='member_nomination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='events.membernomination'),
        ),
    ]
