# Generated by Django 4.2.3 on 2023-07-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название атрибута', max_length=50, verbose_name='Название атрибута')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=10, verbose_name='Название категории')),
                ('description', models.TextField(help_text='Введите описание категории', max_length=100, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Nominations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название номинации', max_length=50, verbose_name='Название номинации')),
                ('cat', models.ManyToManyField(to='mycite.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Номинация',
                'verbose_name_plural': 'Номинации',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя судьи', max_length=100, verbose_name='Имя судьи')),
                ('last_name', models.CharField(help_text='Введите фамилию судьи', max_length=100, verbose_name='Фамилия судьи')),
                ('phone_number', models.CharField(help_text='Введите номер судьи', max_length=11, verbose_name='Номер судьи')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycite.category', verbose_name='Категория')),
                ('nom', models.ManyToManyField(to='mycite.nominations', verbose_name='Номинации')),
            ],
            options={
                'verbose_name': 'Судья',
                'verbose_name_plural': 'Судьи',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя участника', max_length=100, verbose_name='Имя участника')),
                ('last_name', models.CharField(help_text='Введите фамилию участника', max_length=100, verbose_name='Фамилия участника')),
                ('phone_number', models.CharField(help_text='Введите номер участника', max_length=11, verbose_name='Номер участника')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycite.category', verbose_name='Категория')),
                ('nom', models.ManyToManyField(to='mycite.nominations', verbose_name='Номинации')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycite.nominations', verbose_name='Номинация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycite.user', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(help_text='Введите оценку', verbose_name='Оценка')),
                ('atrib', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycite.atribute', verbose_name='Атрибут')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycite.referee', verbose_name='Судья')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycite.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.AddField(
            model_name='atribute',
            name='nom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycite.nominations', verbose_name='Номинация'),
        ),
    ]
